### ISSUE TITLE
Does not compile on Qt 5.4

### ISSUE THREAD

**Issue by mihailescu2m** [mer-hybris/qt5-qpa-hwcomposer-plugin#32]
qeglfspageflipper.h:45:44: fatal error: qpa/qplatformscreenpageflipper.h: No such file or directory

qplatformscreenpageflipper.h seems to be missing from Qt5.4

**Comment by Herrie82** [comment]
Should be fixed with https://github.com/mer-hybris/qt5-qpa-hwcomposer-plugin/pull/80 as well
