### PR TITLE
Initial support for Qt6

### PR DESCRIPTION
**Pull request by Herrie82**
In Qt6 some things with regards to graphics and OpenGL have been moved around a bit. Update the qmake and various header and source files to take care of these changes.

Signed-off-by: Herman van Hazendonk <github.com@herrie.org>

### CODE REVIEW

**Comment by Herrie82** [comment]
Build checked on Qt 5.15.2 and Qt 6.3.0. It might be good to rename this component to a more generic qt-qpa-hwcomposer-plugin as well instead of naming is qt5 specifically.

**Comment by Herrie82** [comment]
@mlehtima @JamiKettunen Any thoughts or comments on this one?

**Comment by JamiKettunen** [comment]
I suppose a port to CMake would be nice but that could be a lot of work, not sure, qmake should stay in the past :p

**Comment by mlehtima** [comment]
Forgot about this PR, I need to verify that it builds without issues with Qt currently used in Sailfish OS but otherwise seems ok.

File: hwcomposer/qeglfsbackingstore.cpp [hunk 1]
```diff
@@ -145,7 +151,7 @@ void QEglFSBackingStore::flush(QWindow *window, const QRegion &region, const QPo
         QRect imageRect = m_image.rect();
 
         QRegion fixed;
-        foreach (const QRect &rect, m_dirty.rects()) {
+        for (const QRect &rect : m_dirty) {
```
Comment (mlehtima) [inline hwcomposer/qeglfsbackingstore.cpp:154]: This fails to build with Qt 5.6. QRegion::begin() needed for using for was introduced in Qt 5.8 https://doc.qt.io/qt-6/qregion.html#begin. This means we need to make this change conditional.

Comment (JamiKettunen) [reply hwcomposer/qeglfsbackingstore.cpp:154]: This looks to be the same change as what I did on #95, should I close my PR in favor of this one? Thanks for testing this though ^^

Comment (Herrie82) [reply hwcomposer/qeglfsbackingstore.cpp:154]: > This fails to build with Qt 5.6 wit error "error: 'begin' was not declared in this scope". QRegion::begin() needed for using for was introduced in Qt 5.8 https://doc.qt.io/qt-6/qregion.html#begin. This means we need to make this change conditional but this can be changed to "for (const QRect &rect : m_dirty.rects())" for Qt < 5.8 afaik. Same for the change below.

I'm happy with either, it's your code in the end, so whatever works for you I'm happy to adjust to that.

Comment (mlehtima) [reply hwcomposer/qeglfsbackingstore.cpp:154]: I would go with "for (const QRect &rect : m_dirty.rects())" for Qt < 5.8 and "for (const QRect &rect : m_dirty)" for Qt >= 5.8 so the difference in the code is easier to see, I tested that the former works with Qt 5.6.

Comment (mlehtima) [reply hwcomposer/qeglfsbackingstore.cpp:154]: @Herrie82 Any plans to fix the build issue mentioned above?

**Comment by Tofee** [comment]
@mlehtima  The commit https://github.com/mer-hybris/qt5-qpa-hwcomposer-plugin/pull/96/commits/6577623330c40114f6f64defc6138769e5548863 should hopefully fix the build for Qt 5.6.

**Review by mlehtima — APPROVED** [review]
